# Generated by Django 4.2 on 2025-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTM_Practise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('variant', models.CharField(max_length=1)),
                ('togri_javob', models.CharField(max_length=1)),
                ('ball', models.IntegerField()),
                ('reyting', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_fan', models.CharField(max_length=120)),
                ('ikkinchi_fan', models.CharField(max_length=120)),
                ('uchinchi_fan', models.CharField(max_length=120)),
                ('tortinchi_fan', models.CharField(max_length=120)),
                ('beshinchichi_fan', models.CharField(max_length=120)),
                ('oltinchi_fan', models.CharField(max_length=120)),
                ('yettinchi_fan', models.CharField(max_length=120)),
                ('sakkizinchi_fan', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('raqam', models.CharField(default='+998', max_length=50)),
                ('hudud', models.CharField(max_length=120)),
            ],
        ),
    ]
