# Generated by Django 4.2 on 2025-12-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanlar',
            name='oltinchi_fan',
        ),
        migrations.RemoveField(
            model_name='fanlar',
            name='sakkizinchi_fan',
        ),
        migrations.RemoveField(
            model_name='fanlar',
            name='yettinchi_fan',
        ),
    ]
