# Generated by Django 4.2 on 2025-12-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fanlar_oltinchi_fan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtm_practise',
            name='reyting',
        ),
        migrations.RemoveField(
            model_name='dtm_practise',
            name='variant',
        ),
        migrations.AddField(
            model_name='dtm_practise',
            name='fan',
            field=models.CharField(default=4.55, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dtm_practise',
            name='ball',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtm_practise',
            name='togri_javob',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='beshinchichi_fan',
            field=models.CharField(default='Tarix', max_length=20),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='birinchi_fan',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Geografiya', 'Geografiya'), ('Fizika', 'Fiziki'), ('Ingliz Tili', 'Ingliz Tili')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='ikkinchi_fan',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Geografiya', 'Geografiya'), ('Fizika', 'Fiziki'), ('Ingliz Tili', 'Ingliz Tili')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='tortinchi_fan',
            field=models.CharField(default='Matematika', max_length=30),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='uchinchi_fan',
            field=models.CharField(default='Ona Tili', max_length=30),
        ),
    ]
