# Generated by Django 4.2 on 2025-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ielts_writing_ieltslistening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTS_listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IELTS_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='ieltslisteninguseranswer',
            name='test',
        ),
        migrations.DeleteModel(
            name='IELTSListening',
        ),
        migrations.DeleteModel(
            name='IELTSListeningUserAnswer',
        ),
    ]
