# Generated by Django 4.2 on 2025-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ielts_listening_ielts_reading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ielts_listening',
            name='audio',
        ),
        migrations.AddField(
            model_name='ielts_listening',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
