# Generated by Django 4.2 on 2025-12-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_ielts_listening_audio_ielts_listening_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ielts_reading',
            old_name='answers',
            new_name='headings',
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='multiple_choice_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='text_answers',
            field=models.JSONField(default=dict),
        ),
    ]
