# Generated by Django 4.2 on 2025-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_answers_ielts_reading_headings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milliy_Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Ingliz Tili', 'Ingliz Tili')], max_length=15)),
                ('savol', models.TextField()),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
