# Generated by Django 4.2 on 2025-12-02 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_milliy_sertifikat'),
    ]

    operations = [
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='togri_variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milliy_sertifikat',
            name='togri_javob',
            field=models.CharField(max_length=120),
        ),
    ]
