# Generated by Django 4.2 on 2025-12-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_milliy_sertifikat_togri_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milliy_sertifikat',
            name='fan',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Ingliz Tili', 'Ingliz Tili')], max_length=20),
        ),
        migrations.AlterField(
            model_name='milliy_sertifikat',
            name='togri_javob',
            field=models.TextField(),
        ),
    ]
