# Generated by Django 4.2 on 2025-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_milliy_sertifikat_fan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ielts_reading',
            name='headings',
        ),
        migrations.RemoveField(
            model_name='ielts_reading',
            name='multiple_choice_answers',
        ),
        migrations.RemoveField(
            model_name='ielts_reading',
            name='text_answers',
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='savol',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='togri_variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variantlar',
            field=models.TextField(default=0),
        ),
    ]
