# Generated by Django 4.2 on 2025-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_ielts_reading_headings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('variantlar', models.TextField()),
                ('togri_variant', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('audio', models.FileField(blank=True, null=True, upload_to='listening_audio/')),
            ],
        ),
        migrations.DeleteModel(
            name='IELTS_listening',
        ),
    ]
