# Generated by Django 4.2 on 2025-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ieltslisteningquestion_delete_ielts_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='SATQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('togri_variant', models.CharField(max_length=255)),
            ],
        ),
    ]
