# Generated by Django 4.2 on 2025-12-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_satquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='satquestion',
            name='togri_javob',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='togri_variant',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
