# Generated by Django 4.2 on 2025-12-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_satquestion_togri_javob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satquestion',
            name='togri_javob',
        ),
        migrations.AddField(
            model_name='satquestion',
            name='variant_a',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satquestion',
            name='variant_b',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satquestion',
            name='variant_c',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satquestion',
            name='variant_d',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
