# Generated by Django 4.2 on 2025-12-20 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_davlat_univer_xorijiy_univer_xususiy_univer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('dtm', 'DTM'), ('ielts_reading', 'IELTS Reading'), ('ielts_listening', 'IELTS Listening'), ('sat', 'SAT'), ('milliy', 'Milliy Sertifikat')], max_length=20)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.FloatField()),
                ('config', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
