# Generated by Django 4.2 on 2025-12-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
