# Generated by Django 4.2 on 2026-01-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_testresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
