# Generated by Django 4.2 on 2026-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RemoveField(
            model_name='ielts_reading',
            name='variantlar',
        ),
        migrations.RemoveField(
            model_name='ieltslisteningquestion',
            name='variantlar',
        ),
        migrations.RemoveField(
            model_name='milliy_sertifikat',
            name='togri_javob',
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='variant_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='variant_b',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='variant_c',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='variant_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='savol',
            field=models.TextField(),
        ),
    ]
