# Generated by Django 4.2 on 2026-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_fanlar_birinchi_fan_alter_fanlar_ikkinchi_fan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='birinchi_fan',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Ingliz Tili', 'Ingliz Tili')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='ikkinchi_fan',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Ingliz Tili', 'Ingliz Tili')], max_length=30),
        ),
    ]
