# Generated by Django 4.2 on 2026-02-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_usertestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Practice your reading skills.')),
                ('duration', models.IntegerField(default=60)),
            ],
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='test_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.readingtest'),
        ),
    ]
