# Generated by Django 4.2 on 2026-02-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_readingtest_ielts_reading_test_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ielts_reading',
            name='test_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.readingtest'),
            preserve_default=False,
        ),
    ]
