# Generated by Django 4.2 on 2026-02-07 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_readingtest_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Practice your reading skills.')),
                ('duration', models.IntegerField(default=60)),
                ('category', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='test_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.listeningtest'),
            preserve_default=False,
        ),
    ]
