# Generated by Django 4.2 on 2026-02-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_listeningtest_ieltslisteningquestion_test_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Practice your sat skills.')),
                ('duration', models.IntegerField(default=60)),
                ('category', models.CharField(choices=[('SAT', 'SAT')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='satquestion',
            name='test_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.sat'),
            preserve_default=False,
        ),
    ]
