# Generated by Django 4.2 on 2026-02-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_sat_satquestion_test_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_reading',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='reading/variants/'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='reading/variants/'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='reading/variants/'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='reading/variants/'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading/questions/'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_text',
            field=models.TextField(default=1, verbose_name='Test matni (Passage)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='category',
            field=models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening')], default='READING', max_length=20),
        ),
    ]
