# Generated by Django 4.2 on 2026-02-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_ielts_reading_image_a_ielts_reading_image_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_reading',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True/False/Not Given')], default='ABCD', max_length=10),
        ),
    ]
