# Generated by Django 4.2 on 2026-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_ielts_reading_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='satquestion',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='sat/variants/'),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='sat/variants/'),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='sat/variants/'),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='sat/variants/'),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='sat/questions/'),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True / False / Not Given')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True / False / Not Given')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_b',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_d',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='savol',
            field=models.TextField(verbose_name='Question text'),
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='variant_a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='variant_b',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='variant_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='satquestion',
            name='variant_d',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
