# Generated by Django 4.2 on 2026-02-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_satquestion_image_a_satquestion_image_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingtest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='title',
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='category',
            field=models.CharField(choices=[('READING', 'Reading')], default='READING', max_length=15),
        ),
    ]
