# Generated by Django 4.2 on 2026-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_writingquestion_writingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='writing/question/'),
        ),
    ]
