# Generated by Django 4.2 on 2026-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_writingquestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='price',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
