# Generated by Django 4.2 on 2026-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_ieltslisteningquestion_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ieltslisteningquestion',
            name='price',
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='price',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
