# Generated by Django 4.2 on 2026-02-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_ieltslisteningquestion_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningtest',
            name='price',
        ),
    ]
