# Generated by Django 4.2 on 2026-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_listeningtest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_reading',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listeningtest',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingquestion',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
