# Generated by Django 4.2 on 2026-02-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0042_ielts_reading_is_paid_ielts_reading_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ielts_reading',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ielts_reading',
            name='price',
        ),
        migrations.AddField(
            model_name='readingtest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.CreateModel(
            name='TestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IELTS_LISTENING', 'IELTS Listening'), ('IELTS_READING', 'IELTS Reading'), ('IELTS_WRITING', 'IELTS Writing'), ('SAT', 'SAT'), ('DTM', 'DTM'), ('MILLIY', 'Milliy')], max_length=30)),
                ('test_id', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'test_id')},
            },
        ),
    ]
