# Generated by Django 4.2 on 2026-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_ielts_reading_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satquestion',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='satquestion',
            name='price',
        ),
        migrations.AddField(
            model_name='sat',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sat',
            name='price',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
