# Generated by Django 4.2 on 2026-02-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_satquestion_is_paid_remove_satquestion_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testaccess',
            name='paid',
        ),
    ]
