# Generated by Django 4.2 on 2026-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_testaccess_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='part',
            field=models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')], default=1),
        ),
    ]
