# Generated by Django 4.2 on 2026-02-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_ieltslisteningquestion_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm_practise',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='dtm/variants/'),
        ),
        migrations.AddField(
            model_name='dtm_practise',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='dtm/variants/'),
        ),
        migrations.AddField(
            model_name='dtm_practise',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='dtm/variants/'),
        ),
        migrations.AddField(
            model_name='dtm_practise',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='dtm/variants/'),
        ),
        migrations.AddField(
            model_name='dtm_practise',
            name='savol_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='dtm/questions/'),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='image_a',
            field=models.ImageField(blank=True, null=True, upload_to='milliy/variants/'),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='image_b',
            field=models.ImageField(blank=True, null=True, upload_to='milliy/variants/'),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='image_c',
            field=models.ImageField(blank=True, null=True, upload_to='milliy/variants/'),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='image_d',
            field=models.ImageField(blank=True, null=True, upload_to='milliy/variants/'),
        ),
        migrations.AddField(
            model_name='milliy_sertifikat',
            name='savol_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='milliy/questions/'),
        ),
    ]
