# Generated by Django 4.2 on 2026-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_dtm_practise_image_a_dtm_practise_image_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/maps/'),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Matching'), ('MAP', 'Map / Diagram Labelling')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True / False / Not Given'), ('MATCH', 'Matching Headings'), ('FILL', 'Fill in the Blank')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='togri_variant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='togri_variant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='variant_a',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='variant_b',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='variant_c',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='variant_d',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='category',
            field=models.CharField(choices=[('LISTENING', 'Listening')], default='LISTENING', max_length=20),
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='description',
            field=models.TextField(default='Practice your listening skills.'),
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='duration',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='sat',
            name='category',
            field=models.CharField(choices=[('SAT', 'SAT')], default='SAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sat',
            name='description',
            field=models.TextField(default='Practice your SAT skills.'),
        ),
    ]
