# Generated by Django 4.2 on 2026-02-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_ieltslisteningquestion_map_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='part',
            field=models.IntegerField(choices=[(1, 'Passage 1'), (2, 'Passage 2'), (3, 'Passage 3')], default=1),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='passage_text',
            field=models.TextField(verbose_name='Passage matni'),
        ),
    ]
