# Generated by Django 4.2 on 2026-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_readingtest_part_readingtest_passage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingtest',
            name='part',
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='part',
            field=models.IntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4')], default=1),
        ),
    ]
