# Generated by Django 4.2 on 2026-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_readingtest_part_ielts_reading_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='testaccess',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
