# Generated by Django 4.2 on 2026-02-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milliy_sertifikat',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='milliy_sertifikat',
            name='price',
        ),
    ]
