# Generated by Django 4.2 on 2026-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_dtm_majburiy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTM_Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(choices=[('Matematika', 'Matematika'), ('Ona Tili', 'Ona Tili'), ('Tarix', 'Tarix'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Ingliz Tili', 'Ingliz Tili')], max_length=20)),
                ('turi', models.CharField(choices=[('ixtisoslik', 'Ixtisoslik fani'), ('majburiy', 'Majburiy fan')], default='ixtisoslik', max_length=15)),
                ('savol', models.TextField()),
                ('savol_rasm', models.ImageField(blank=True, null=True, upload_to='dtm/questions/')),
                ('variant_a', models.CharField(default='', max_length=255)),
                ('variant_b', models.CharField(default='', max_length=255)),
                ('variant_c', models.CharField(default='', max_length=255)),
                ('variant_d', models.CharField(default='', max_length=255)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='dtm/variants/')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='dtm/variants/')),
                ('image_c', models.ImageField(blank=True, null=True, upload_to='dtm/variants/')),
                ('image_d', models.ImageField(blank=True, null=True, upload_to='dtm/variants/')),
                ('togri_variant', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='DTM_Majburiy',
        ),
    ]
