# Generated by Django 4.2 on 2026-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_dtm_majburiy_delete_dtm_savol'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='passage_text_2',
            field=models.TextField(blank=True, default='', verbose_name='Passage 2 matni'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_text_3',
            field=models.TextField(blank=True, default='', verbose_name='Passage 3 matni'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_title_2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Passage 2 sarlavha'),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_title_3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Passage 3 sarlavha'),
        ),
        migrations.AlterField(
            model_name='readingtest',
            name='passage_text',
            field=models.TextField(verbose_name='Passage 1 matni'),
        ),
    ]
