# Generated by Django 4.2 on 2026-03-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_readingtest_passage_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_e',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading v'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_f',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading vi'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_g',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading vii'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_h',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading viii'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_i',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading ix'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_j',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading x'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_k',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading xi'),
        ),
        migrations.AddField(
            model_name='ielts_reading',
            name='variant_l',
            field=models.CharField(blank=True, max_length=500, verbose_name='Heading xii'),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True / False / Not Given'), ('YNNG', 'Yes / No / Not Given'), ('MATCH', 'Matching Headings'), ('FILL', 'Fill in the Blank')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='variant_d',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
