# Generated by Django 4.2 on 2026-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_ielts_reading_variant_e_ielts_reading_variant_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_reading',
            name='word_box',
            field=models.TextField(blank=True, default='', help_text='Faqat FILLBOX turida. Masalan: Mexicans,random,rotating,despite,preserve', verbose_name='Word Box (vergul bilan ajrating)'),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('TFNG', 'True / False / Not Given'), ('YNNG', 'Yes / No / Not Given'), ('MATCH', 'Matching Headings'), ('FILL', 'Fill in the Blank'), ('FILLBOX', 'Fill in the Blank with Word Box')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ielts_reading',
            name='togri_variant',
            field=models.CharField(max_length=1000),
        ),
    ]
