# Generated by Django 4.2 on 2026-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_ielts_reading_word_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_e',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Variant E'),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_f',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Variant F'),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_g',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Variant G'),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_h',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Variant H'),
        ),
        migrations.AddField(
            model_name='ieltslisteningquestion',
            name='variant_i',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Variant I'),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='question_type',
            field=models.CharField(choices=[('ABCD', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MATCH', 'Matching'), ('MAP', 'Map / Diagram / Image'), ('CHECK', 'Checkbox (Multiple Select)')], default='ABCD', max_length=10),
        ),
        migrations.AlterField(
            model_name='ieltslisteningquestion',
            name='togri_variant',
            field=models.CharField(help_text="ABCD → 'A'; CHECK → 'A,C,F' (vergul bilan); FILL → erkin matn", max_length=200),
        ),
    ]
