# Generated by Django 4.2 on 2026-01-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
