# Generated by Django 4.2 on 2026-01-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
