# Generated by Django 4.2 on 2026-01-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_email_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
