# Generated by Django 4.2 on 2026-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_user_alter_usertestresult_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
