# Generated by Django 4.2 on 2026-02-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_free_trial_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestresult',
            name='is_completed',
        ),
    ]
