# Generated by Django 4.2 on 2026-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_usertestresult_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
