# Generated by Django 4.2 on 2026-02-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_badge_profile_consecutive_perfect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='consecutive_perfect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_test_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='streak_days',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viloyat',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
