# Generated by Django 4.2 on 2026-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_profile_badge_profile_consecutive_perfect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
